name: CD-PROD

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['CI-PROD']
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Run docker-compose
        run: |
          sudo apt-get update && sudo apt-get install sshpass
          sshpass -p '${{ secrets.SSH_PASSWORD }}' ssh -v -o StrictHostKeyChecking=no root@109.199.101.105 <<'ENDSSH'
          apt install awscli --silent
          aws configure set aws_access_key_id ${{ secrets.AWS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SEC }}
          aws configure set default.region us-east-1
          aws s3 cp s3://${{ secrets.AWS_BUCKET }}/docker-compose.yml docker-compose.yml
          export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          export GITHUB_SHA=${{ github.sha }}
          docker pull yagosilvadev/mensagemdodia:${{ github.sha }}
          docker-compose down
          docker-compose up -d

      - name: Check the deployed service
        uses: jtalk/url-health-check-action@v4
        with:
          url: http://api.mensagemdodia.com/api/categories/featured
          follow-redirect: false # Optional, defaults to "false"
          max-attempts: 60
          retry-delay: 10s
          retry-all: false # Optional, defaults to "false"
