name: CI-PROD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      #
      #      - name: Log in to Docker Hub
      #        uses: docker/login-action@v2
      #        with:
      #          username: ${{ secrets.DOCKER_USERNAME }}
      #          password: ${{ secrets.DOCKER_PASSWORD }}
      #
      #      - name: Build and push Docker image
      #        uses: docker/build-push-action@v2
      #        with:
      #          context: .
      #          file: ./Dockerfile
      #          push: true
      #          tags: yagosilvadev/mensagemdodia:${{ github.sha }}

      - name: Upload docker-compose yml to s3
        shell: bash
        env:
          aws_key_id: ${{ secrets.AWS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SEC }}
          aws_s3_bucket: ${{ secrets.AWS_BUCKET }}
        run: |
          sudo apt-get update && sudo apt-get -y install awscli
          aws configure set aws_access_key_id $aws_key_id
          aws configure set aws_secret_access_key $aws_secret_access_key
          aws configure set default.region us-east-1
          aws s3 cp docker-compose.yml s3://$aws_s3_bucket/
